FROM arm64v8/debian

# ==== Basic setup ====
RUN apt -qq update
RUN apt -qq -y install git curl build-essential python wget

WORKDIR "~"
RUN curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install_nvm.sh
RUN bash install_nvm.sh
RUN . ~/.nvm/nvm.sh   # to make nvm usable from shell